### ISSUE TITLE
URLs with consecutive hyphens aren't working

### ISSUE THREAD

**Issue by saadmb** [nfrasser/linkifyjs#464]
### Example

This is a working website: [hp--community.force.com](https://hp--community.force.com/).

```javascript
linkify.test('hp--community.force.com'); // returns false. Expected to be true
linkify.test('hp-community.force.com'); // returns true
```

**Comment by nfrasser** [comment]
@saadmb apologies for the delayed reply, the fix for this is now available in the latest v4.2.0 release.
