### ISSUE TITLE
BUG: linkifyStr doesn't work with apostrophe and an alphabetical character

### ISSUE THREAD

**Issue by patrickReiis** [nfrasser/linkifyjs#488]
I am using Deno.

I work with a technology called [nostr](https://nostr.com/), and the following string `nostr:npub1gujeqakgt7fyp6zjggxhyy7ft623qtcaay5lkc8n8gkry4cvnrzqd3f67z` is converted to `patrick`.

However, if the string I just mentioned has an apostrophe plus another character it doesn't work.

Like this: `nostr:npub1gujeqakgt7fyp6zjggxhyy7ft623qtcaay5lkc8n8gkry4cvnrzqd3f67z's`

I actually created a new repository just dedicated for this issue, in the line 32 you can change the argument so it becomes the variable in the line 27 or 28.

Link: https://github.com/patrickReiis/linkify-mention  

I could try to fix this on my own, since I have a specific parser with `{render: {url: <specific-parser>}}`, but I think it should work under the hood already, without me having to worry about it.

**Comment by nfrasser** [comment]
@patrickReiis apologies for the delayed reply, the fix for this is now available in the latest v4.2.0 release.

**Comment by patrickReiis** [comment]
Thanksssssss

**Comment by xyzshantaram** [comment]
It would probably make the most sense as a config flag so everyone is happy

**Comment by nfrasser** [comment]
Change has been reverted in the latest v4.3.0, PRs welcome to make this more customizable. @patrickReiis you might also consider making a custom plugin for this case inserted of specifying a custom scheme. See [packages](https://github.com/nfrasser/linkifyjs/tree/main/packages) for examples.
