### ISSUE TITLE
Object Replacement Characters not being sanitized

### ISSUE THREAD

**Issue by alexvcasillas** [nfrasser/linkifyjs#495]
Hey there, I'm Alex from [Tiptap](https://tiptap.dev) 👋🏻 

I wanted to upstream this issue to you as it's something that's affecting `linkifyjs` directly. It seems that `linkifyjs` does not handle properly the sanitization of a string when it comes to the `find` method that looks for link matches within a string. Here's an example of this character: `\uFFFC` this is an [object replacement character](https://www.fileformat.info/info/unicode/char/fffc/index.htm) and it looks like an empty string to the naked eye but if you pass something like `find('https://google.com this)` (where the space between the .com and this is the given character `\uFFFC`) the method will return you that the link is `https://google.com this` which some might say it's correct as it's a valid unicode character but people will be very confused by this as we've been by the reports we were having in our editor repo.

Just wanted to upstream this to you to see if it's something that you'd consider adding to the `find` method or to help anyone that might be having this issue so they know what could be about.

This was the issue in which we ended up discovering this https://github.com/ueberdosis/tiptap/issues/5679 just in case you're curious what this could potentially cause :)

Hope you have a great day 🙇🏻

**Comment by nfrasser** [comment]
Hi Alex, thanks for reporting! This should be a doable fix, linkify can interpret `\uFFFC` as whitespace and therefore exclude anything that comes after it from the link. Will update here when the fix is available.

**Comment by alexvcasillas** [comment]
Thank you @nfrasser 🙇🏻

**Comment by nfrasser** [comment]
@alexvcasillas fix is available in the latest v4.2.0 release.
