### ISSUE TITLE
Chrome extension using linkifyjs rejected by Chrome Store

### ISSUE THREAD

**Issue by nikkimontoya** [nfrasser/linkifyjs#505]
I use TipTap editor which uses linkifyjs as a dependency in my Chrome extension. After review, the extension was rejected by Chrome Store reviewers. The reason is that the extension contains obfuscated code which violates [this](https://developer.chrome.com/docs/webstore/troubleshooting/#obfuscation) rule. It turns out that the obfuscated code comes from linkifyjs, particularly from tlds.mjs, which contains encoded strings. Could you somehow adapt your library so it complies with the Chrome Store rules?

**Comment by nfrasser** [comment]
Hi @nikkimontoya, tlds.mjs contains an encoded list [top-level domains](https://data.iana.org/TLD/tlds-alpha-by-domain.txt) that's [written here](https://github.com/nfrasser/linkifyjs/blob/v4.2.0/tasks/update-tlds.js#L157-L170) and [decoded here](https://github.com/nfrasser/linkifyjs/blob/v4.2.0/packages/linkifyjs/src/scanner.mjs#L51-L56)

This is implemented to reduce the final bundle size (background: #416)

Providing two versions of linkify that include either encoded or plain TLDs would significantly complicate the build system, so unfortunately I cannot commit to implementing and maintaining this for just this one use case. Feel free to either

1. Fork this repo and build your own version of it with plain TLDs, or
2. Pin your linkify version to v4.0.2, the last version to include plain TLDs.

**Comment by ocxo** [comment]
> I cannot commit to implementing and maintaining this for just this one use case

[Socket.dev](https://socket.dev/) (popular open source supply chain, security tool) is flagging this library as potentially malicious due to the obfuscated code
