### ISSUE TITLE
Strings containing links starting with http:// and wrapped in html tags are parsed incorrectly

### ISSUE THREAD

**Issue by aadil-shaikh-agileinfoways** [nfrasser/linkifyjs#507]
String containing links starting with http://  and wrapped in html tags are parsed incorrectly

Steps to reproduce:
```
const userInput1= '<a href="www.google.com">Google</a>'
const userInput2= '<a href="https://www.google.com">Google</a>'
      <Linkify>
      {userInput1}     // Works; extracted link='https://www.google.com'  
      {userInput2}    // Fails; extracted link='www.google.com">Google</a>'
      </Linkify>
```

Any fix for this?

**Comment by nfrasser** [comment]
Hi @aadil-shaikh-agileinfoways, are you using `linkify-react` for this? I am unable to reproduce this:
https://codepen.io/nfrasser/pen/mdOaOmR

Are you using `linkifyjs` or `linkify-string`? These do not support parsing HTML by default. You have to use [`linkify-html`](https://linkify.js.org/docs/linkify-html.html), [`linkify-element`](https://linkify.js.org/docs/linkify-element.html), [`linkify-react`](https://linkify.js.org/docs/linkify-react.html). Or you could use another HTML parser plugin before processing text nodes with linkify. 

Quick example: https://codepen.io/nfrasser/pen/dyOwOQO

**Comment by aadil-shaikh-agileinfoways** [comment]
Sorry I gave a wrong example. I have updated the example now. Can `linkify-html` help in this case?

**Comment by nfrasser** [comment]
Okay, I see. This happens because linkify-react can't parse HTML strings. You can use `linkify-html` along with React's [dangerouslySetInnerHTML](https://react.dev/reference/react-dom/components/common#dangerously-setting-the-inner-html). Example here: https://codepen.io/nfrasser/pen/emOEEVP (though be careful about [cross-site scripting attacks](https://linkify.js.org/docs/xss.html))

**Comment by nfrasser** [comment]
Hi @uggrock, unfortunately `linkify.find` only works on plain text strings, it cannot parse HTML. Please pre-process your text with an HTML parser (e.g., the [native DOMParser](https://developer.mozilla.org/en-US/docs/Web/API/DOMParser/parseFromString)) and only provide text nodes to `linkify.find`.
